version: "3.8"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
      ETCD_SNAPSHOT_COUNT: "50000"
      ETCD_MAX_REQUEST_BYTES: "104857600"
      ETCD_HEARTBEAT_INTERVAL: "500"
      ETCD_ELECTION_TIMEOUT: "2500"
    volumes:
      - etcd_data:/etcd
    networks:
      - milvus-net

  minio:
    image: minio/minio:latest  # ใช้เวอร์ชันล่าสุดแทน
    container_name: milvus-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio_data:/data
    networks:
      - milvus-net

  pulsar:
    image: apachepulsar/pulsar:2.10.2
    container_name: milvus-pulsar
    command: bin/pulsar standalone
    volumes:
      - pulsar_data:/pulsar/data
    networks:
      - milvus-net

  milvus:
    image: milvusdb/milvus:v2.4.1
    container_name: milvus
    command: ["milvus", "run", "mixture"]
    environment:
      ETCD_ENDPOINTS: "etcd:2379"
      MINIO_ADDRESS: "minio:9000"
      PULSAR_ADDRESS: "pulsar://pulsar:6650"
    ports:
      - "19530:19530"
    depends_on:
      - etcd
      - minio
      - pulsar
    networks:
      - milvus-net

volumes:
  etcd_data:
  minio_data:
  pulsar_data:

networks:
  milvus-net:

